{% set version = "8.1.0" %}

package:
  name: pydash
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pydash/pydash-{{ version }}.tar.gz
  sha256: 30914c3e9d377ea2cd0d3c0a4f252889b08392f730a5eb4d117e5b598cdf1d52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - pydash
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dgilland/pydash
  license: MIT
  license_file: LICENSE.rst
  summary: The kitchen sink of Python utility libraries for doing "stuff" in a functional way.
  description: The kitchen sink of Python utility libraries for doing stuff in a functional way. Based on Lo-Dash JS library
  doc_url: https://pydash.readthedocs.io/en/latest/
  dev_url: https://github.com/dgilland/pydash

extra:
  recipe-maintainers:
    - souravsingh
    - dbast
